# Generated by Django 5.0.3 on 2024-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_station', models.CharField(max_length=255)),
                ('jumia_link', models.URLField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
